# version: '3'

services:
  rabbit:
    container_name: nameko-example-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql:
    container_name: nameko-example-mysql
    image: mysql:5.7
    ports:
      - "3309:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "borobudur_hotel_jakarta"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
     - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  merlynn_park_hotel:
    build: ./borobudur_hotel_jakarta
    container_name: borobudur_hotel_jakarta
    depends_on:
      - rabbit
      - mysql
    ports:
      - "8006:8000"
    links:
      - "rabbit:nameko-example-rabbitmq"
      - "mysql:nameko-example-mysql"
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_HOST: "mysql"
      MYSQL_DB: "borobudur_hotel_jakarta"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

  gateway:
    build: ./gateway
    container_name: gateway3
    depends_on:
      - rabbit
    ports:
      - "8007:8000"
    links:
      - "rabbit:nameko-example-rabbitmq"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
